### ISSUE TITLE
Feather Roadmap

### ISSUE THREAD

**Issue by khcrysalis** [khcrysalis/Feather#26]
## Roadmap
- [x] Implement basic localizations
  - [ ] Translate all available languages in the project
  - [ ] (Try to) localize every single bit of text inside of the project
  - [x] Add force localization changer in settings (will be available next release)
  - [ ] Sync all localizations in project
#  
- [ ] Fix any potential import errors
- [ ] Warn the user if the certificate used is expired or revoked
- [ ] Allow user to access a webpage to allow installation from other devices
- [ ] Migrate to new zip framework for higher levels of compression

###### *more to be added!* | Probably next release version: 1.1.4

#

**Comment by AushevAhmad** [comment]
I recommend pinning this issue for easier access :3

**Comment by schweppes-0x** [comment]
Great roadmap, but I can't see any priorities, what will happen when or in what order. 

if it were up to me, I'd suggest the following order:

1. ESign certificates + DNS -> https://github.com/khcrysalis/Feather/issues/4 
2. Add sorting options for version, date, etc. In Stores
3. Clean up messy URL 
4. Batch import and export sources
5. URL Scheme for feather
6. Add notices
7. Localizations

**Comment by khcrysalis** [comment]
Hey there's no order! we will get to it when we can!

**Comment by khcrysalis** [comment]
Stuff like esign certificates require tons of research, so please don't try to force me or other people to try and do it as a number one priority.

**Comment by schweppes-0x** [comment]
Hey, I totally get it! I didn’t mean to come across as pushing or forcing anything, just wanted to share my thoughts and priorities based on what might be impactful. I appreciate all the work you’re doing on this project and am excited to see how things progress

**Comment by Stetsed** [comment]
Hey, some feature suggestions I would love to see within Feather, esign no-log is currently my signer of choice(with me also having acces to the MapleSigner v3 beta esign is still my preffered right now).

Some things I would love to see in feather are:
- Allow adding suffix/prefix to the apps by default, I like having all my apps appended with "Maple" or another indicator to tell me "Hey, it's signed by that".
- Allow background download support, this is a major one as it's pretty annoying that the app download just stops and breaks if you exit the app, this is the major reason I am still using esign cuz it doesn't have issues in this department. The signing part generally is fine as who cares it's quick, but downloading especially from certain places can be very slow.
- Allow naming certificates, it would be great if we could name our certificates to give more overview/info on what they are, and maybe also would be nice if we could export them back into there p12/mobileprovision format for use inside of other applications or saving them/sending them to another device.

Adding to the 

> Trying to support esign exported sources is unlikely as they're encrypted.

I have today looked into this with Eevee from the MapleSign discord(not affiliated to them in any way). And from what we could find they are not using encryption instead they are using obfuscation. The lines you get with the export are base64 encoded, I was able to convert this into raw byte code and was able to find that when I export 2 sources which both start with "https://raw.githubusercontent.com/" the first 34 bytes(Each charachter is a byte in this case we assume UTF-8), where identical.

As such we can make the assumption that they are using some sort of static obfuscation instead of encryption. This is as far as I got for this time. However this may be able to be used as a starting point for other people as it seems like the hardest part is finding the static variables to reverse it. I might take another shot at it soon but for now this is the info that we got.

I hope you lads all have a wonderful day further.

**Comment by lpuv** [comment]
Adding on to the last person, it would be great if you could select which certificate you wanted to use while signing!

**Comment by susandahal** [comment]
Support for .esign certificate can be kept at lower priority since the same certificate are available in p12 format in applep12 certificate. Higher priority should be given to ability to signing the apps with revoked certificate since not everyone has access to the live certificate bought from vendors

**Comment by Spritzerland** [comment]
add qol check for entitlements for feather's own cert it was signed with, if the cert doesn't support app icon changing then remove the section

**Comment by Spritzerland** [comment]
add source[] support for mass importing repositories, like how esign used to do it

**Comment by khcrysalis** [comment]
@Spritzerland 
> add source[] support for mass importing repositories, like how esign used to do it
unlikely to happen, these format is obfuscated and only meant to work on esign. Just import all the repos manually.

**Comment by khcrysalis** [comment]
> add qol check for entitlements for feather's own cert it was signed with, if the cert doesn't support app icon changing then remove the section

I don't find much use for this, I'll keep the section available regardless

**Comment by khcrysalis** [comment]
> Support for .esign certificate can be kept at lower priority since the same certificate are available in p12 format in applep12 certificate. Higher priority should be given to ability to signing the apps with revoked certificate since not everyone has access to the live certificate bought from vendors

@susandahal feather already can sign apps with revoked certificates, its only the installation thats an issue.

**Comment by susandahal** [comment]
> > Support for .esign certificate can be kept at lower priority since the same certificate are available in p12 format in applep12 certificate. Higher priority should be given to ability to signing the apps with revoked certificate since not everyone has access to the live certificate bought from vendors
> 
> @susandahal feather already can sign apps with revoked certificates, its only the installation thats an issue.

It seems to be working now after few changes

**Comment by khcrysalis** [comment]
I only said that because iOS is the one that manages the installation, iOS is the one that determines if it should be installed/opened

If you use a dns trick it should work as with any other tool that has local installation

**Comment by fwzea** [comment]
Could you add some of the following things in the next update:

Downloads don’t stop when out of the app

Redirect to photos instead of files when changing a icon in the signer

Upload Dates for apps on repos

And this![image](https://github.com/user-attachments/assets/b9294078-2349-4e49-bd0a-af95c98c4a49)

**Comment by nklowns** [comment]
> Downloads don’t stop when out of the app

I'd love to have this feature

**Comment by GottaLoveAng** [comment]
cant really be added since theres no way to differentiate one tweak between other tweaks and etc. due to the same bundleid. would likely cause your screen to be filled with different apps unrelated to the one you're attempting to update depending on your repos.

**Comment by NoozPrime** [comment]
Love your app i wish you guys courage and motivation to work on the app you guys have great potential in making this app bigger !

**Comment by ismailcarlik** [comment]
It would be better if we use String Catalog for localization because in its current state, after each merge operation, each translator has to check the native language translation file line by line, which is extremely tiring. As can be seen from the sample screenshot, if we switch to this, the translation process will become extremely easy.

<img width="862" alt="image" src="https://github.com/user-attachments/assets/af3550ff-c19d-4a3c-afc7-11ab98dab2a5">

**Comment by khcrysalis** [comment]
> It would be better if we use String Catalog for localization because in its current state, after each merge operation, each translator has to check the native language translation file line by line, which is extremely tiring. As can be seen from the sample screenshot, if we switch to this, the translation process will become extremely easy.

Issue with the string catalog is that it requires Xcode for convenience, which not many people have access to.

**Comment by MrAlucardDante** [comment]
Support for Altstore V2/Sidestore source format would also be great 

https://faq.altstore.io/developers/make-a-source

https://docs.sidestore.io/docs/advanced/app-sources

**Comment by castdrian** [comment]
> Support for Altstore V2/Sidestore source format would also be great 

The altsource spec is already fully supported

**Comment by castdrian** [comment]
> > > feather says that the JSON is invalid

I can repro this, visually it looks fine and altstore accepts it so I'm gonna have a guess and say this is a parsing issue on our side, ideally opening an issue to track this would be the best action to take

**Comment by khcrysalis** [comment]
@MrAlucardDante 

Looking through your source, it seems it does not follow the altstore spec because it does not include an identifier for the repository, heres https://cdn.altstore.io/file/altstore/apps.json

<img width="541" alt="Image" src="https://github.com/user-attachments/assets/9d6fe5d3-51b3-4c52-be78-8fdcc27d7df6" />

Feather uses identifiers to be able to distinguish between repositories, so once you add this key to your file it will add fine.

**Comment by khcrysalis** [comment]
You have also posted a screenshot to sidestores documentation, which also includes a identifier you need to add, which again you have not done so yet.
<img width="998" alt="Image" src="https://github.com/user-attachments/assets/2357a975-7b52-4784-96ec-bab87525bbfa" />

**Comment by MrAlucardDante** [comment]
> You have also posted a screenshot to sidestores documentation, which also includes a identifier you need to add, which again you have not done so yet.
> <img width="998" alt="Image" src="https://github.com/user-attachments/assets/2357a975-7b52-4784-96ec-bab87525bbfa" />

Thanks for help. It will try that. The identifier part is missing from the altstore documentation as well as the example source they provide, that's probably why I never set it. Maybe that's a mistake on their end.
